### ISSUE TITLE
Pokemon from earlier Gen

### ISSUE THREAD

**Issue by deisuke1234** [kwsch/PKHeX#405] opened 2016-11-14 19:23 UTC
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.LegalityAnalysis.getLegalityReport() in C:\Users\perham\Desktop\PKHeX-master\PKHeX\Legality\Analysis.cs:line 141
   at PKHeX.LegalityAnalysis..ctor(PKM pk) in C:\Users\perham\Desktop\PKHeX-master\PKHeX\Legality\Analysis.cs:line 52
   at PKHeX.Main.updateLegality(LegalityAnalysis la) in C:\Users\perham\Desktop\PKHeX-master\PKHeX\MainWindow\Main.cs:line 2653
   at PKHeX.Main.updateOriginGame(Object sender, EventArgs e) in C:\Users\perham\Desktop\PKHeX-master\PKHeX\MainWindow\Main.cs:line 2288
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll

PKHeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\perham\Desktop\PKHeX-master\PKHeX\bin\x86\ClickOnce-Debug\PKHeX.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=sv, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_sv_b77a5c561934e089\System.Windows.Forms.resources.dll

System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll

System.Deployment.resources, Version=4.0.0.0, Culture=sv, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment.resources\v4.0_4.0.0.0_sv_b03f5f7f11d50a3a\System.Deployment.resources.dll

mscorlib.resources, Version=4.0.0.0, Culture=sv, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_sv_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by evandixon** [comment] 2016-11-14 20:00
Caused by abnormal code path, where pk.GenNumber is 6 but pk is of type PK7.

**Comment by kwsch** [comment] 2016-11-14 20:51
Type check causes it to not check anything, then assigning it as "Parsed"; when trying to check the move legality status it would check vs null.

Correct fix is to never explicitly assign Parsed as true, instead check if there's any parse results.

**Closed** 2016-11-14 20:52 UTC
