### ISSUE TITLE
Language in Trainer Data still cannot be set as CHT or CHS

### ISSUE THREAD

**Issue by 139god** [kwsch/PKHeX#357] opened 2016-11-10 01:04 UTC
Please add it, ty.

**Comment by evandixon** [comment] 2016-11-10 01:09
Duplicate of #345

Have you tried the latest build?  (Say "log in as guest" if prompted)
http://teamcity.uniquegeeks.net/repository/download/PKHeX_PKHeXBuildPr/2859:id/PKHeX%20Build%20602.zip

**Comment by 139god** [comment] 2016-11-10 01:35
@evandixon In pokemon editor the language option is nine
What I said is in the Trainer Info section, where you can set the start time, ID, played hours, etc

**Comment by ericjwg** [comment] 2016-11-10 02:32
fixed

**Closed** 2016-11-10 02:36 UTC
