### ISSUE TITLE
Shedinja Marked As Illegal

### ISSUE THREAD

**Issue by ultima-soul** [kwsch/PKHeX#1813] opened 2018-02-04 22:18 UTC
Looking at my Diamond save file and I found a Shedinja marked illegal. I also re-tested the evolution (by de-evolving my Ninjask to Nincada) and came up with the same problem for the new Shedinja.

[Relevant PK4.zip](https://github.com/kwsch/PKHeX/files/1693372/Relevant.PK4.zip)

From what I know, PKHex should display no gender for Shedinja while still having the same PID as Ninjask.
Shedinja displays genderless just fine in-game.

You can compare with RoC's Shedinja: https://github.com/ReignOfComputer/RoCs-PC/blob/master/09%20-%20Gen%20IV%20-%20DPPt%20Collection/292%20-%20Shedinja.pkm

And Ninjask: https://github.com/ReignOfComputer/RoCs-PC/blob/master/09%20-%20Gen%20IV%20-%20DPPt%20Collection/291%20-%20Ninjask.pkm

**Comment by ultima-soul** [comment] 2018-02-04 22:34
Just to add. Decided to inject the Nincada into Platinum and tested the evolution. The Shedinja generated there is fine. There may be a difference in how DP handle things and how PtHGSS may handle it.

[Platinum New Shedinja.zip](https://github.com/kwsch/PKHeX/files/1693390/Platinum.New.Shedinja.zip)

**Comment by kwsch** [comment] 2018-02-04 23:35
Per the [structure](https://projectpokemon.org/docs/gen-4/pkm-structure-r65/) & data of the original Shedinja, it has a Female gender:
![image](https://user-images.githubusercontent.com/6393368/35783641-84f09682-09bf-11e8-85e4-1c574fe1c93f.png)

RoC's PC one has genderless:
![image](https://user-images.githubusercontent.com/6393368/35783654-ac981af2-09bf-11e8-83f9-6e63a4b3acd2.png)

I was able to find something related to this on Bulbapedia:
https://bulbapedia.bulbagarden.net/wiki/Talk:Shedinja_(Pokémon)#Gender

>When I use the name rater, despite being genderless, Shedinja will have a gender when we write a new nickname. Wouldn't that be a nice information for trivia? Gabriel Rocha (Diby esp) 02:19, 5 June 2009 (UTC)

>>I have confirmation of this... If someone can determine where the gender comes from this would be great. At the moment I'm picking the same gender as your Nijask. — THE TROM — 03:24, 6 June 2009 (UTC)

It would appear that this is an undocumented glitch in that the game knows how to hide the current Shedinja gender in most displays, but wasn't checked for (at least) the nickname rater -- which shows the gender of the original Nincada. Probably gets fixed when traded up to gen 5.

I can make an exclusion for this quirk if it's confirmed to be fixed after transferred.

**Comment by Lusamine** [comment] 2018-02-05 00:24
I've noticed a similar problem except it was a Nincada I retail transferred into Heart Gold and evolved.  The resulting Shedinja appeared genderless but was male when opened in PKHex.  Once traded back to Platinum, it becomes genderless again.

Perhaps it's DP and HGSS that handle Shedinja gender incorrectly, but Platinum does it correctly?

I'm unable to transfer a gendered Shedinja to Gen 5 at the moment to verify if it's fixed through Poketransfer since my only avenue right now is through Platinum, where the bug isn't bugged.

**Comment by ultima-soul** [comment] 2018-02-05 00:39
I tested the evolution on SS. Same problem so that confirms that DP and HGSS likely have this bug, but Platinum doesn't. I'll try PokeTransfer in a bit.

**Comment by ultima-soul** [comment] 2018-02-05 01:27
Here's the problem Shedinja transferred and also Ninjask for comparison. Seems like PokeTransfer fixes it.

[PokeTransfer PK5.zip](https://github.com/kwsch/PKHeX/files/1693546/PokeTransfer.PK5.zip)

**Closed** 2018-02-05 02:13 UTC
