### ISSUE TITLE
Hoenn Starters illegal with non-Pokeball with Gen 6 origin

### ISSUE THREAD

**Issue by amish995** [kwsch/PKHeX#1520] opened 2017-10-11 14:47 UTC
All hoenn starters are reporting as illegal using the current commit of PKHeX. Any ball other that pokeball is shown as illegal. However, other balls should be possible to breed down.
Proof:
https://i.imgur.com/IN0h7sr.png

**Comment by sora10pls** [comment] 2017-10-11 14:50
Other Balls can be bred down, you’re correct. The list below helps a lot

https://www.serebii.net/games/pokeball.shtml

**Comment by architdate** [comment] 2017-10-11 15:11
Yeap ^^ the proper event would be the dream world hoenn starters event where any available pokeball could be used to catch the starters. The same can be applied to sinnoh starters too which are also atm illegal

**Comment by kwsch** [comment] 2017-10-11 15:58
>Hoenn Starters illegal ... with Gen 6 origin

The Hoenn starters were never released as female in the Dream World.

Ball inheritance rules:
* Starting in Generation VI, the Poké Ball of the female Pokémon will be passed down to its offspring. 
* In Generation VII, if a male and female Pokémon of the same species are bred, the offspring will have an equal chance of inheriting either parent's Poké Ball.
* **Despite being able to produce offspring of either species when bred together, Nidoran♀/Nidoran♂ and Volbeat/Illumise are still considered different species and the male's Poké Ball will not be inherited when breeding with its female counterpart.**

Working as intended ;)

**Closed by kwsch** 2017-10-11 15:58 UTC

**Comment by architdate** [comment] 2017-10-11 16:28
Nvm my mistake, its working as intended

**Comment by amish995** [comment] 2017-10-11 16:40
Yep. My bad. Totally forgot the Ball passing mechanics were different.
