### ISSUE TITLE
Legal Pokemon caught in game being flagged as Illegal

### ISSUE THREAD

**Issue by deadair3210** [kwsch/PKHeX#2573] opened 2019-12-09 16:07 UTC
**Describe the problem**
I have 4 Pokemon that show as illegal in some way or another, mostly invalid moves. I have caught all of these legitimately in the game.

**To Reproduce**
PKM files attached 

**Expected behavior**
Legal pokemon to be listed as legal

**Screenshots**

**Additional context**
[Illegal Pkm.zip](https://github.com/kwsch/PKHeX/files/3940577/Illegal.Pkm.zip)

**Comment by kwsch** [comment] 2019-12-10 03:30
Sneasel fixed in latest commit; the other 3 are probably downleveled raids (insufficient badges).

**Comment by deadair3210** [comment] 2019-12-10 05:03
Are the downleveled raids incorrect in some way or are they just not handled correctly yet?

**Comment by kwsch** [comment] 2019-12-10 05:11
Just not handled correctly yet 👍 

Need to nail down how exactly things get downleveled / any restrictions / etc...

**Comment by deadair3210** [comment] 2019-12-10 05:15
Aah, ok. was just curious, love knowing the behind the scenes stuff in games

**Comment by legareal** [comment] 2019-12-13 23:46
Likewise there appears to be something falsely illegal about this Grimmsnarl.

Getting invalid moves on a couple of TMs.

[861 - Grimmsnarl.pk8.zip](https://github.com/kwsch/PKHeX/files/3963114/861.-.Grimmsnarl.pk8.zip)

**Comment by slp32** [comment] 2019-12-26 20:13
I also have some Pokemon being shown as illegal.
[PK8.zip](https://github.com/kwsch/PKHeX/files/4003385/PK8.zip)
The Gyarados and Ferrothorn were caught from the wild area and had nothing done to them, while the Ribombee was a Cutiefly from the wild area which I used a Rare Candy on, and now Quiver Dance is showing up as an invalid move.

**Comment by kwsch** [comment] 2019-12-26 20:35
@legareal That's a hacked pkm; working as intended. Please only report un-modified data.

**Closed** 2019-12-26 20:59 UTC
Labels: bug
