### ISSUE TITLE
Adding an Update Button

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#208] opened 2016-08-30 01:39 UTC
Is it possible to add in a check for updates or that we can automatically download the new version?

**Comment by evandixon** [comment] 2016-08-30 02:08
Duplicate of #199

The current status of deploying with ClickOnce (which comes with automatic updates):
- Need @kwsch to respond to my notes in #199 about future releases.
- Need to change location of PKM database of ClickOnce deployments.  The proper way of doing this breaks Mono compatibility, and my only other current ideas feel like hacks, at best.
- I have a build system set up to automatically do deployments if @kwsch tags releases with version numbers ("X.Y.Z", where X, Y, and Z are integers).  It should™ work, more testing is needed.

**Closed by evandixon** 2016-08-30 02:08 UTC
