### ISSUE TITLE
[Legality Issue] Gen 4

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1525] opened 2017-10-17 18:20 UTC
Ursaring with Avalanche (Gen 4 TM) currently reads as illegal when obtained from all of the Gen 4 games.
Thanks for taking the time to read this, and for all your work with PKHeX. Tested on build 3883.

**Comment by sora10pls** [comment] 2017-10-17 18:51
Could you upload the PKM? I'm unable to replicate.

![image](https://user-images.githubusercontent.com/17801814/31683272-88658c4e-b34a-11e7-8aea-c5b67e15d659.png)
![image](https://user-images.githubusercontent.com/17801814/31683282-90cfb936-b34a-11e7-8793-59c585a99348.png)

**Comment by kwsch** [comment] 2017-10-17 19:26
Probably met level is too low, implying transferred as Teddiursa then evolves in gen5+.
Working as intended

**Closed by kwsch** 2017-10-17 19:26 UTC

**Comment by greenDarkness** [comment] 2017-10-17 23:18
You were right. My mistake.
Thank you for the help!
