### ISSUE TITLE
Shaymin is flagged illegal in BDSP

### ISSUE THREAD

**Issue by T3chTobi** [kwsch/PKHeX#3308] opened 2021-11-22 11:12 UTC
**Describe the bug**
Shaymin is currently flagged illegal in BDSP, but it is possible to obtain in the game with this glitch: https://www.youtube.com/watch?v=w1kqSeaFsGE

**Expected behavior**
Shaymin should be flagged as legal now

**Screenshots**
Here is a video on youtube showing the process on how to obtain Shaymin: https://www.youtube.com/watch?v=w1kqSeaFsGE

**Comment by ReignOfComputer** [comment] 2021-11-22 11:12
>Glitch
🤡🤡🤡

**Comment by murrty** [comment] 2021-11-22 11:39
Shaymin is flagged as legal, though. Have you tried transferring from previous events?

**Comment by Lusamine** [comment] 2021-11-22 12:03
Pokemon that are only obtainable with cheats and glitches are not considered legal.  Working as intended.

**Closed by Lusamine** 2021-11-22 12:03 UTC
Labels: bug
