### ISSUE TITLE
Generated GO Pokémon don't have a pokéball or GO stamp in Home

### ISSUE THREAD

**Issue by IXpatch** [kwsch/PKHeX#3868] opened 2023-04-23 10:19 UTC
**Bug description**
When generating GO Pokémon in BDSP and SWSH using the Encounter Database, the generated Pokémon, when transferred to Pokémon Home, won't have their Pokéball displayed in the mobile version of Home, nor will they have the GO Stamp in the console version of Home.

**To Reproduce**
Use the Encounter Database to generate a Pokémon from GO, then transfer it to Pokémon Home. View it from the boxes (no game connected) on the console version of Home to see it does not have a GO Stamp, or from the mobile version of Home to see it does have a blank space where its Pokéball should be.

**Expected behavior**
I'm not sure if the "GO Stamp" is reproducible for Pokémon that have not actually been imported from GO via GO, but the Pokéball should definitely be displayed correctly in Home. There must be something wrong with how GO Pokémon are generated for this bug to occur.

**Screenshots**
![Screenshot_20230423_121149_Pokmon HOME](https://user-images.githubusercontent.com/78077450/233833900-8ffb2645-2ba8-465f-a0db-a5010d451631.jpg)

**Comment by Lusamine** [comment] 2023-04-23 10:27
This is not a bug. Data like this is created by Pokemon HOME when a Pokemon is legitimately transferred from GO to HOME. When you create a Pokemon in another game instead, that data isn't included. And no, you cannot forge it because that data is exclusively created and stored in HOME. 

This is why best practice is to only create Pokemon from the original game. Creating a Legends: Arceus Pokemon in SWSH or a gen3 Deoxys in BDSP causes similar problems. When you move a non-native Pokemon into HOME, the app expects there to be extra data and can't find it, so you get the wonky display you see.

Transfer your Pokemon legitimately if you want them to appear legitimate.

**Closed by Lusamine** 2023-04-23 10:27 UTC
Labels: bug
