### ISSUE TITLE
BattleSlot Lock not working as intented?

### ISSUE THREAD

**Issue by egzonqj** [kwsch/PKHeX#691] opened 2017-01-01 16:52 UTC
So well, I tried once again this feature and I guess it isn't working as it should be? (or maybe I don't understand how it works at all).

And when I tried few things like changing the locked slot, this happened
![image](https://cloud.githubusercontent.com/assets/5099644/21582062/33773f68-d04a-11e6-9f82-c52ea038337e.png)
and after changing box, the Pokémon itself is not anymore on the slot but after swapping with the locked icon once again, it returns to be locked. 

But in-game that's not the case (unless you change to battlebox mode), and you can change the slot of the Pokémon even if it is battlelocked (i guess this is automatically changed in the battlebox).

Also, you can now modify again the Pokémon that has a battle slot,
![image](https://cloud.githubusercontent.com/assets/5099644/21582096/07c340b4-d04b-11e6-979d-cf6ccb07582a.png)

**Comment by kwsch** [comment] 2017-01-01 17:00
Working as intended.
![image](https://cloud.githubusercontent.com/assets/6393368/21582121/b55c167e-d000-11e6-9d62-8f76bdafb563.png)

A slot can be assigned to a team, which is what the purple icon shows. Only once the **team is locked** is the slot prevented from editing.

**Closed by kwsch** 2017-01-01 17:00 UTC
