### ISSUE TITLE
Missing Microsoft.NetCore.App version 7.0.0

### ISSUE THREAD

**Issue by otavio-silva** [kwsch/PKHeX#4077] opened 2023-11-27 02:34 UTC
**Describe the bug**
The README says that .NET 7.0 is required and links to the appropriate page, but the application says that .NET 7.0.0 is required.
I can build using `dotnet build`, `dotnet build -c Debug` and `dotnet build -c Release` with no issues or warnings but using `dotnet run` gives the warning in the screenshot. Calling `"C:\Program Files\dotnet\dotnet.exe" PKHeX.WinForms\bin\Release\net7.0-windows\win-x64\PKHeX.dll` directly gives the desired result.
**To Reproduce**
1. `git clone https://github.com/kwsch/PKHeX.git`
2. `dotnet build -c Release`
3. `cd PKHeX.WinForms\`
4. `dotnet run`

**Expected behavior**
Application to launch coorectly.

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/22914610/bd63c766-1c83-4567-96be-52eb94f3d624)

**Additional context**
There are multiple .NET versions installed:
1. SDK is installed by `scoop install main/dotnet-sdk`
2. Runtimes installed though `choco install dotnet-*.0-desktopruntime`, versions 6, 7 and 8 are installed.

**Comment by otavio-silva** [comment] 2023-11-28 02:48
@kwsch running `dotnet sdk check` gives the following:
```cmd
SDKs do .NET:
Versão       Status
------------------------
8.0.100      Atualizado.

Runtimes do .NET:
Nome                              Versão      Status
---------------------------------------------------------
Microsoft.AspNetCore.App          8.0.0       Atualizado.
Microsoft.NETCore.App             8.0.0       Atualizado.
Microsoft.WindowsDesktop.App      8.0.0       Atualizado.


As últimas versões do .NET podem ser instaladas de https://aka.ms/dotnet-core-download. Para obter mais informações sobre os ciclos de vida do .NET, confira https://aka.ms/dotnet-core-support.

```
I was expecting that because it's the latest version. Where does your `dotnet` command points to? That might be the issue on my machine.

**Comment by kwsch** [comment] 2023-11-28 04:53
```
C:\>where dotnet
C:\Program Files\dotnet\dotnet.exe
```

I recently added a branch for changing the repo to use .NET 8 instead of .NET 7 (to be merged sometime in the next couple weeks); dunno if your results would be different with that.

**Comment by drvictorvs** [comment] 2023-11-29 19:22
I had the same issue. I don't have admin permission, so I had to use winget to get dotnet, but the problem is having a preinstalled system version that for some reason takes priority over the user one even if the user is higher in the PATH. What has been working for me is to call the user dotnet on the PKHeX dll.

**Comment by drvictorvs** [comment] 2023-11-29 19:24
I had the same issue on TrinityModLoader. I don't have admin permission, so I had to use winget to get dotnet, but the problem is having a preinstalled system version that for some reason takes priority over the user one even if the user is higher in the PATH (and shows that way upon where.exe dotnet). What has been working for me is to call the user dotnet.exe on the Trinity dll (literally just "%AppData%/Microsoft/dotnet/dotnet.exe X:/path/to/Trinity.dll")

**Comment by otavio-silva** [comment] 2023-11-30 18:55
Can confirm that the `net8` branch works as intended.

**Closed as completed** 2023-12-04 04:15 UTC
Labels: question
