### ISSUE TITLE
Can Trainer Info Be Edited for Gen 4 Games?: Conversion from .DUL to .SAV to .DUL Causes Game Save Corruption

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#244] opened 2016-09-08 05:21 UTC
I don't know if this is an error or not, but every time I change the trainer info and places back into the game, it causes the screen to go black and be stuck after the journal entries. I am using Pokemon Diamond and Pearl as examples.

NOTE: I am using Action Replay DSi and converting the .DUC to .SAV and back again. I just don't know if this is a program error or an error in the conversion process.

**Comment by suloku** [comment] 2016-09-08 06:18
Have you made sure that the oroginal duc->sav conversion works before any pkhex editing?

**Comment by ricksee** [comment] 2016-09-08 12:06
@suloku Yea it showed that it was a success. When I went to edit the information, I changed the name, Trainer ID and Secret ID and the amount of cash just to see. Then I turned it back to .DUC and injected it onto the game. It boots up normally, and it includes the name change at the start screen. After exiting the journal entries, the screen remains black. I was using a 16GB memory card for Action Replay DSi.

I was hoping the program would at least consider other formats to support, such as .DUC like Pokegen.

**Comment by suloku** [comment] 2016-09-08 14:00
I meant if you tested duc->sav->duc without any editing to sort out if the problem was the conversion.

**Comment by sora10pls** [comment] 2016-09-08 16:22
If you're giving yourself max cash, refer to my latest #245. Perhaps that could be causing the crash?

**Comment by ricksee** [comment] 2016-09-08 17:55
@sora10pls No, no max cash like 999999, just added 2 more zeroes to it from 15000 to 1500000. 

@suloku No, but I will let you know real quick.

**Comment by evandixon** [comment] 2016-09-08 18:19
1,500,000 is greater than the max of 999999, so the issue may be related.

Also, I doubt save conversion is the issue.  The only difference between duc and raw is that duc has a header with metadata at the beginning.

**Comment by ricksee** [comment] 2016-09-08 18:26
@suloku Ok so what I did was created a new game save and I saved at the first point in my house in Twinleaf Town. It successfully converted into a .SAV file named Diamond.sav for Pokemon Diamond. However, when I tried to open it in PKHeX, it gave me an error:
![see](https://cloud.githubusercontent.com/assets/21182549/18361150/c7040c88-75ce-11e6-89e8-88db15f2210e.png)

I wasn't using this to edit, just to see if PKHeX was able to open it. It did not.

The program I am using to convert the files is Offline Save Format Converter v. 2.6. I selected Action Replay DSi as the source format and converted it to a Raw Format with Auto-detect as the default size. 

When I converted Pearl.sav back to .DUL I used game name Pokemon Diamond and filename as Diamond2. When it restored it in Action Replay, it brought back my save without any problems at all. 

Either 1) My retail game copy is no good.
          2) My Action Replay DSi is no good.
          3) My DS Lite is no good.
         4) The converter or the formats I am using are no good.
        5) I must have made a mistake in the naming of the files.
       6) PKHeX is not supporting the conversion.

**Comment by ricksee** [comment] 2016-09-08 18:29
@evandixon I filed in all the values that were possible to that program so that might have been the case. PKHeX allowed me to fill it all in so that might have been an issue.

**Comment by kwsch** [comment] 2016-09-08 18:31
Save twice before trying to edit your save file. Past gen games store two copies of the save file, and if one is not initialized then it's tripping the save recognition up.

**Comment by ricksee** [comment] 2016-09-08 18:32
@kwsch Before you close this Is it save twice from the game or twice from Action Replay?

**Comment by kwsch** [comment] 2016-09-08 18:34
Preferrably save -> soft reset -> save.

**Comment by ricksee** [comment] 2016-09-08 18:36
@kwsch So I am going to open my game and save again, soft reset, save again, and then backup. Let me get a minute.

**Comment by ricksee** [comment] 2016-09-08 18:55
@kwsch I can confirm that saving, then resetting, then saving again does help PKHeX recognize the conversion. However, when it is opened, the boxes are colored red, probably meaning since I just started the game and I didn't open my PC for the first time, it is unavailable.

![sac](https://cloud.githubusercontent.com/assets/21182549/18362230/f04ba23c-75d2-11e6-8103-125e90de9974.png)


So the only thing that I edited was my name, putting into all capital letters and my cash from 3000 to 30000. Then I saved the changes can converted them back to .DUL. When I restored them, the changes were applied and the game still works. However I didn't changed everything like TID, SID, adventure info, game started and hall of game date, gender or anything else so I still don't know what will happen. Plus, just to be on the safe side, I also think the max cash is 6 figures and not 7, so you might want to change that. Also, the direction when you use the keyboard arrow keys is reversed.

**Comment by ricksee** [comment] 2016-09-08 18:59
So would that mean I would have to do this method every time I want to make an edit?

**Comment by ricksee** [comment] 2016-09-08 19:05
@kwsch What about gen 5 games?

**Comment by kwsch** [comment] 2016-09-09 02:59
No, you just need to make sure the save file is completely initialized.

The red boxes are obviously indicating that the box hasn't been initialized by the game, I wouldn't set anything in the box in the event that the game resets it when it initializes the region.

**Comment by ricksee** [comment] 2016-09-09 04:57
@kwsch What do you mean by initialized?

**Comment by suloku** [comment] 2016-09-09 05:54
Basically, there are featured that won't correctly work until a certain point in the game because the game has not yet stored any info in the savegame.

**Comment by ricksee** [comment] 2016-09-09 13:37
@kwsch At what point would that be in order to make edits without saving twice.

**Comment by kwsch** [comment] 2016-09-09 15:38
The whole saving twice thing only has to be done once; both save files have to be initialized.

**Comment by ricksee** [comment] 2016-09-09 16:26
@kwsch So how to initialize them.

**Comment by sora10pls** [comment] 2016-09-09 16:55
I'd say play up until the catching tutorial with Dawn. After it's done, do as Kaphotics said earlier:

Save -> soft reset -> save

After that, test the save file in PKHeX and see if it's working as intended.

**Comment by ricksee** [comment] 2016-09-09 17:14
@sora10pls So after doing that and doing the saving twice I can save normally after?

**Comment by sora10pls** [comment] 2016-09-09 17:20
Like Kaphotics said, yes.

"The whole saving twice thing only has to be done once"

**Comment by ricksee** [comment] 2016-09-09 17:41
@sora10pls Ok will do. I just had to make sure.

**Comment by ricksee** [comment] 2016-09-09 20:12
@sora10pls It is still red. Do I have to catch a Pokemon and put it in the box?

**Comment by ricksee** [comment] 2016-09-09 20:21
Nevermind storing a Pokemon in the box corrects the problem.

**Comment by ricksee** [comment] 2016-09-09 23:26
@sora10pls @kwsch After doing what you guys said, it is confirmed that at least after that point, the game can be edited without saving twice. I had to put a Pokemon in the box in order to remove the red from the boxes. 

It seems that saving, soft resetting, then saving again can make it work if you are trying to edit the game for the first time, especially if you are using Action Replay. Or if you are playing early in the game, doing this method before or by the time Dawn/Lucas teaches you how to catch. I believe this prevents the corruption. 

However, it should note the max money can be 999,999 and not at seven figures. This might also caused the corruption. 

Now I am wondering @sora10pls @kwsch that would this apply to Platinum and the Gen V games as well?

It would be alot easier if the program would be able to allow opening other save formats such as .DUC, like Pokegen did. It would save alot of time but it is your choice.

**Comment by ricksee** [comment] 2016-09-10 01:18
@kwsch If I decided to upload a new 100% save file, would I have to save twice again?

**Comment by sora10pls** [comment] 2016-09-10 01:18
The max money limit issue was already resolved in [this commit.](https://github.com/kwsch/PKHeX/commit/f0d13da35a2475c89c94fce4dd9d1f34d7f85010)

**Comment by ricksee** [comment] 2016-09-10 02:25
@sora10pls Thanks.

**Closed** 2016-09-10 21:24 UTC
