### ISSUE TITLE
WC3 Eggs Fateful Encounter

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1469] opened 2017-09-19 18:02 UTC
So it looks like if a WC3 Egg (PCJP 2004, PCJP 2005, and PCNY WISH) is traded to R/S and hatched there, it loses its fateful encounter flag.  It does not change game origins though.

I am thinking we should implement a way to know this, and in legality put something like:
"Traded as an egg and hatched on Ruby/Sapphire"

**Comment by kwsch** [comment] 2017-09-19 18:37
"looks like" isn't proof enough to warrant a change; will need to know at which stage the fateful encounter flag is lost (obedience egg E/FRLG -> RS, or obedience egg RS -> hatch), if at all.

There's two different types of "fateful encounter"; one being the met location (0xFE ?) and another being the obedience flag (which is the real fateful encounter flag). This obedience flag is not set when received by RS, hence the fateful/non-fateful observed. 

Remember that the obedience flag is not set when the met location of an egg is changed (on hatch), or if the met location is Fateful and it is transferred to gen4.

https://github.com/kwsch/PKHeX/blob/6611e874c39aa8da0906f48b0cd1e80b45e8b60e/PKHeX.Core/PKM/PK3.cs#L251

**Comment by kamronbatman** [comment] 2017-09-19 19:01
I tested it, and that is what happens.  Sorry for using such a weak word. :)

**Comment by kwsch** [comment] 2017-09-19 19:02
At what point does it lose the obedience flag? Trade or hatching?

**Comment by kamronbatman** [comment] 2017-09-19 19:02
I updated my comment above.  Specifically hatching but only in R/S.

**Comment by kwsch** [comment] 2017-09-20 02:17
Confirmed ingame behavior with hacked specimens; all Fateful Encounter (obedience) flags were cleared in Ruby/Sapphire.

**Closed** 2017-09-20 02:18 UTC
