### ISSUE TITLE
Flag unavailable species in older SWSH savefile revisions as illegal

### ISSUE THREAD

**Issue by Atrius97** [kwsch/PKHeX#3482] opened 2022-04-16 10:59 UTC
**Is your feature request related to a problem? Please describe.**
PKHeX allows you to insert species that aren't available in the base game, such as Zarude, IoA, or CT species, into savefiles from older game versions that did not yet have those pokemon coded into the game.

Currently, if these Pokemon satisfy legality requirements to be legal in the current version of SWSH, these Pokémon are flagged as legal in older savefile revisions as well, despite being a species that's unavailable legitimately in that savefile revision.

**Describe the solution you'd like**
If possible to flag based on savefile revision, it would be useful if said species were flagged as illegal when an older savefile is loaded, if the species didn't exist in that savefile revision at the time. 

Some error message along the lines of "Species unavailable in current savefile revision" would be best, but the typical "incorrectly transferred" message used for incompatible cross-generation transfers would suffice.

**Additional context**
As a sidenote, this could also potentially answer the reoccurring user complaint of "why does this legal pokemon appear as a Pikachu, it's supposed to be in SWSH" for those who are playing the SWSH cart's base game version and cannot/have not updated.

**Comment by sora10pls** [comment] 2022-04-16 11:04
Duplicate of #2920

**Comment by Atrius97** [comment] 2022-04-16 11:08
> Duplicate of #2920

Ah, I hadn't seen that this had been requested previously. It had come to mind but I wanted to wait until after the BDSP and PLA updates had slowed down, since it seemed low priority.

**Closed** 2022-04-16 15:05 UTC
Labels: enhancement
