### ISSUE TITLE
Past gen Pokemon Memories not saving

### ISSUE THREAD

**Issue by CyraFen** [kwsch/PKHeX#870] opened 2017-02-19 03:29 UTC
When I try to edit the the nonOT memories of a Pokemon from Gen VI or before, and put it into the box, the memory will not save when I view the Pokemon's information again. Is this an issue or am I just not doing something correctly?

**Comment by kwsch** [comment] 2017-02-19 08:21
Unable to replicate described issue. Be sure you are using the latest release / commits.

**Comment by CyraFen** [comment] 2017-02-19 16:18
![past gen memory 1](https://cloud.githubusercontent.com/assets/25874350/23104079/f46c68ae-f694-11e6-94ea-5cf7832e7867.PNG)
![past gen memory 2](https://cloud.githubusercontent.com/assets/25874350/23104081/f8b5216c-f694-11e6-8302-3a65a2ebc394.PNG)

I made sure that I clicked save after the first picture, but when I set the pokemon into the box and view its info again, the memory randomized itself again. Is this a mechanic with the memories that I'm not aware of?

**Comment by kwsch** [comment] 2017-02-19 19:20
Transferring 6->7 sets the default poke bank memory. Thus no other memory value is correct.

**Comment by CyraFen** [comment] 2017-02-20 01:03
okay, so is the default bank memory "The Pokemon seems to have a good memory, but doesnt seem to remember..." or is it whatever memory it had in gen vi? I'm sorry I'm asking so many questions >.<

**Comment by sora10pls** [comment] 2017-02-20 02:43
Pokemon memories for those with Gen 1 origin in Gen 7:


Pokemon memories for those with Gen 1-6 origin in Gen 7 (notOT):
![image](https://cloud.githubusercontent.com/assets/17801814/23110052/2b2159b6-f6ec-11e6-91a5-f79137c1ff80.png)

Pokemon memories for those with Gen 6 origin in Gen 7 (OT):
Whatever memories they had in Gen 6 are carried over.

Pokemon memories for those with Gen 7 origin:
![image](https://cloud.githubusercontent.com/assets/17801814/23110040/11b413c4-f6ec-11e6-9210-a5e144a78e67.png)

This is not a bug, as Kaphotics said the memories are set by default by PKHeX for transferred Pokemon.

**Closed** 2017-02-20 02:48 UTC
