### ISSUE TITLE
Wrong encounter slot/seed for a few Unown from gen 3

### ISSUE THREAD

**Issue by ymaniz09** [kwsch/PKHeX#4332] opened 2024-07-29 21:03 UTC
**Describe the bug**
Currently I'm using [pokebot-gen3](https://github.com/40Cakes/pokebot-gen3) to shiny hunt Unowns.
A few of them are being marked with an `X` in front of the origin seed.
Since they were not manipulated/edited, I believe there should be a bug on calculating the origin seed.  

**Screenshots**
![image](https://github.com/user-attachments/assets/0a611330-22ae-4c7a-8612-b2dbf8f56697)
![image](https://github.com/user-attachments/assets/a51c561f-c484-46ca-8562-a1b87a80ec7a)

I checked this one on PokeFinder:
![image](https://github.com/user-attachments/assets/10283278-005d-4cc4-b8e1-7642a9e97b84)

**Comment by Lusamine** [comment] 2024-07-29 21:12
This is not a bug.

The X means Synchronize failed, not that it couldn't calculate a seed. You can see that your Unown have a green check mark, which means at least one legal seed+lead was found. If multiple possible seeds+lead exist, the program can't tell which one created it, but the requirement to be legal is at least one works.

**Comment by ymaniz09** [comment] 2024-07-29 21:15
Thank you so much for this detailed explanation!

**Comment by kwsch** [comment] 2024-07-30 05:24
I'm not sure the explanation is correct; if it was a synch fail, it would say so. 

The X usually indicates a failure to find a method H starting point. I'll check how the program is resolving it in about a week. Vblanks can disjoint the correlation, hence why X isn't flagged illegal like in Gen4.

**Comment by ymaniz09** [comment] 2024-07-30 12:03
I have multiple bots shiny hunting on Gen 3. I just noticed the X in a very, very few Pokémon. Please let me know if you need any further information.

**Comment by Lusamine** [comment] 2024-07-30 13:52
> I'm not sure the explanation is correct; if it was a synch fail, it would say so.

You're right. I confused the "X" notation with the "Synchronize: X" notation. Reopening for more investigation later.

**Closed** 2024-08-07 22:03 UTC
Labels: question
