### ISSUE TITLE
Legal Pokemon flagged as illegal when transferred to Battle Revolution

### ISSUE THREAD

**Issue by Remiccino** [kwsch/PKHeX#1690] opened 2017-12-03 15:56 UTC
Hi, I was opening my Platinum save, which is an unmodified save freshly pulled from the cart, to pull some of my Pokemon to use within Pokemon Battle Revolution, when this issue occurred. As can be seen from the screenshot, the Pokemon is perfectly legal in Platinum, but not in PBR, due to an ability PID mismatch. I would like to inquire as to why this might happen (PBR using outdated DP legality checks?). Thank you for your time.

![image](https://user-images.githubusercontent.com/33729347/33527086-dd5148ac-d88d-11e7-8116-8a2f32fd1e29.png)

**Comment by kwsch** [comment] 2017-12-03 16:07
Probably reading the IVs wrong.
Big Endian encoding vs the regular Little Endian encoding; would need to see examples of IVs in one vs the other (not transferred by PKHeX).

**Comment by Remiccino** [comment] 2017-12-03 16:19
If this is the case, then would this problem occur selectively? As you can see, out of the 6 Pokemon I pulled from my Platinum save, only 2 encountered the problem and others remained legal. 
However, something I have noticed is, it only occurs if the Pokemon has its 2nd slot ability, and the 2nd slot is different from the 1st slot. If both slots are the same ability, as with Milotic and Mamoswine, it turned out okay.
How could I assist you on this, if possible? I no longer have access to a Wii, as I gave it away after being unable to connect it to my 3DS for transfer (hence I resorted to using emulation). I could give you the saves used here, but unfortunately not a PBR save that contains the same Pokemon authentically transferred from DS to Wii.

**Comment by kwsch** [comment] 2017-12-03 18:20
PKM files as zipped attachments help reproduce the issue while debugging :)
Just drag out the pkm from boxes (don't load to tabs).

Need to figure out which field is causing the misbehavior...

**Comment by kwsch** [comment] 2017-12-03 20:25
yup, is IVs
![image](https://user-images.githubusercontent.com/6393368/33529386-08a8f46e-d825-11e7-91f9-fbe7498d28f1.png)

Just being read in the wrong order

**Closed** 2017-12-03 20:40 UTC

**Comment by kwsch** [comment] 2017-12-03 20:58
There are a few behaviors of the PBR transfer to note:

- Transfer is 1 way
- Transfer gets rid of non-DP forms
- Transfer doesn't transfer items or PtHGSS Met Locations

Instead of reworking a lot of internals to handle gen3/4->PBR (present format) checking, PKHeX will just flag anything that was transferred incompletely by the game. Since the transfer is 1 way (and no online remains), PKHeX won't completely mimic the game copy-transfer so that a backwards transfer can be done at a later time.
