### ISSUE TITLE
Shiftry Sucker Punch bug

### ISSUE THREAD

**Issue by ominousacid** [kwsch/PKHeX#1927] opened 2018-05-05 20:49 UTC
Shiftry learns Sucker Punch by Pt/HGSS Move Tutor but it does not work (see attached images). Odaxis verified that the PKM file I sent him seems legit.
![shiftry 1](https://user-images.githubusercontent.com/39014302/39667437-7bd2918e-50b6-11e8-9d28-946469d8672e.png)
![shiftry 2](https://user-images.githubusercontent.com/39014302/39667438-7be850a0-50b6-11e8-8842-dc94bc626d48.png)

**Comment by architdate** [comment] 2018-05-05 21:24
Working as intended. If the level is 14+ then it works. 
Shiftry learns sucker punch in DPPt as a Tutor Move. Shiftry is only possible at level 14 minimum. (seedot evolves to nuzleaf at level 14, can be immediately evolved to shiftry with a leaf stone) 
Only then can it can learn the tutor move (seedot does not learn it)
The met level is set at the level when the poketransfer occurs, so it can only be transferred with sucker punch with level >= 14. Hopefully its cleared. 

Issue ready to be closed

**Comment by sora10pls** [comment] 2018-05-05 22:05
>the PKM file I sent him seems legit
>seems

;)

**Closed** 2018-05-05 23:45 UTC
