### ISSUE TITLE
Random Pokemon marked as seen when loading the Pokedex of Pokemon Emerald. 

### ISSUE THREAD

**Issue by zmarotrix** [kwsch/PKHeX#1687] opened 2017-12-03 09:33 UTC
When I load a brand new save of Pokemon Emerald right after getting the Pokedex, it has several Pokemon marked as seen that do not appear in game.

**Comment by sora10pls** [comment] 2017-12-03 13:59
Probably a duplicate of #1660

**Closed** 2017-12-03 15:03 UTC
